spring.application.name=devatlas

github.token=${GITHUB_TOKEN:}

spring.datasource.url=${DB_URL:jdbc:h2:file:./data/devatlas;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true