CREATE TABLE profile_analysis_history
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    username                 VARCHAR(100)             NOT NULL,

    overall_score            INTEGER                  NOT NULL,
    level                    VARCHAR(30)              NOT NULL,

    total_repositories       INTEGER                  NOT NULL,
    excellent_repositories   BIGINT                   NOT NULL,
    good_repositories        BIGINT                   NOT NULL,
    developing_repositories  BIGINT                   NOT NULL,

    strongest_repository     VARCHAR(255),

    analyzed_at              TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT chk_history_overall_score
        CHECK (overall_score BETWEEN 0 AND 100),

    CONSTRAINT chk_history_total_repositories
        CHECK (total_repositories >= 0)
);

CREATE INDEX idx_history_username_analyzed_at
    ON profile_analysis_history (
                                 username,
                                 analyzed_at
        );